### ISSUE TITLE
Duo Sandbox Windows 11 23H2 PRO ( 22631.4391 ) Sandboxed instance not working

### ISSUE THREAD

**Issue by SpaceDandy28** [DuoStream/Duo#178] opened 2024-10-31 17:18 UTC
It appears that something is wrong with the hyper V switch settings. I've tried uninstalling DUO deleting all files. Enable and Disable windows sandbox and hyper-v restarting between attempts with no avail. The issue seems to persist constantly. I know others had issues with the sandbox instance who have AMD graphics card and want to verify that this might be my issue as well since I am currently running an RX 6800 XT. I have tried DUO on the same windows build on my laptop with an NVIDIA RTX 2060 and it works perfectly. 
<img width="622" alt="DUO error" src="https://github.com/user-attachments/assets/bdc081f1-d339-4542-914f-f21ad9de9a14">
<img width="636" alt="DUO Errors" src="https://github.com/user-attachments/assets/b5dc5283-47d4-48cc-bd1f-890676c45a34">
<img width="651" alt="Duo Erros 2" src="https://github.com/user-attachments/assets/c904add5-bf7e-4870-997f-e51dc198db8c">

**Comment by zzfuture** [comment] 2024-11-09 11:28
Duplicate of #161

**Comment by SpaceDandy28** [comment] 2024-11-10 00:24
> Duplicate of #161

Yeah looks like it was the AMD driver issues. Updated windows, but remained on 23H2 and now sandbox works.

**Closed** 2024-11-10 00:24 UTC
