### ISSUE TITLE
v1.3.0 "Failed to apply the display driver patch for Duo"

### ISSUE THREAD

**Issue by agustinmorantes** [DuoStream/Duo#47] opened 2024-02-14 19:49 UTC
I have the same issue explained in #30 in the latest version, however the RDPWrapper config is correctly configured, with network level authentication, and updating the INI and restarting TermService don't fix the problem. Also tried restarting the PC.
Sunshine was not installed standalone, and I created a new local user for Duo. Windows defender real-time protection is disabled via group policy.

![image](https://github.com/DuoStream/Duo/assets/21344464/57c93fd8-c5c2-41fc-b8e5-851e6f4b181c)

![image](https://github.com/DuoStream/Duo/assets/21344464/faa30ce4-56f1-4985-a148-380cd91ac824)

![image](https://github.com/DuoStream/Duo/assets/21344464/0c68c5ee-870a-4ce6-9fd4-48a2fb770c74)

![image](https://github.com/DuoStream/Duo/assets/21344464/56746a2b-ca5d-469f-b5ac-a3d119d68cc2)

![image](https://github.com/DuoStream/Duo/assets/21344464/aa64a207-fb56-4c0e-ba43-24404b914ad7)

**Comment by DeadFrostt** [comment] 2024-02-16 05:49
Same issue.

**Comment by Black-Seraph** [comment] 2024-02-16 15:06
That error message alone doesn't tell us very much.

You see, this error can occur even if everything works absolutely as intended, as it is thrown every time a hook timing error occurs, which simply means that Duo will retry the hook again and again until the timing is right and the hook grips properly.

Your RdpWrap install seems to be configured correctly and the same is true for your Duo instance configuration, from what I can tell at least.

If possible attach a full application event log export and a copy of the instance's Sunshine log file, if there is one.
It can be found in **C:\Program Files\Duo\config** and should be named after your instance.

**Comment by DeadFrostt** [comment] 2024-02-16 19:43
> That error message alone doesn't tell us very much.
> 
> 
> 
> You see, this error can occur even if everything works absolutely as intended, as it is thrown every time a hook timing error occurs, which simply means that Duo will retry the hook again and again until the timing is right and the hook grips properly.
> 
> 
> 
> Your RdpWrap install seems to be configured correctly and the same is true for your Duo instance configuration, from what I can tell at least.
> 
> 
> 
> If possible attach a full application event log export and a copy of the instance's Sunshine log file, if there is one.
> 
> It can be found in **C:\Program Files\Duo\config** and should be named after your instance.

Thank you for your reply! My C:\Program Files\Duo\config folder does not exist At all ive tried reinstalling duo but nothing seems to work.

**Comment by Black-Seraph** [comment] 2024-02-17 13:05
Please retry with 1.3.1 and report back.

There was an edge case where the WDDM driver instance wouldn't start properly that got fixed in that build that could have very much caused your issue.

**Comment by DeadFrostt** [comment] 2024-02-17 21:19
1.3.1 gives the same error. Tried uninstalling duo and then installing too, dosent make a difference.

**Comment by Black-Seraph** [comment] 2024-02-17 23:19
Are there any other Duo messages in the application event log?

And is the computer part of a domain?

**Comment by gjunnila** [comment] 2024-02-18 02:52
Same issue with the same config on a fresh fresh install. Tried the same steps as @DeadFrostt.
Only Duo message in application event log is "Failed to apply the display driver patch for AndroidDevice1" with AndroidDevice1 being the instance and display name.

**Comment by Black-Seraph** [comment] 2024-02-18 13:11
I have a hunch what it could be but I'd have to take a look at an affected host myself via TeamViewer or such.

Is anyone willing to let me take a look?

**Comment by gjunnila** [comment] 2024-02-18 21:09
I can give you access to my machine. How would I go about contacting you privately?

**Comment by Black-Seraph** [comment] 2024-02-18 21:38
You can always send an email to admin@black-seraph.com, I'm the only one that has access to that inbox and we can take it from there if needed.

Also, disabling the iGPU shouldn't be necessary, I'd really appreciate it if you could re-enable the iGPU and try producing some useful log files / application event log outputs for us to debug this issue further.

**Comment by Black-Seraph** [comment] 2024-02-19 11:16
For those affected by this issue, please try this new [test build](https://drive.google.com/file/d/1I8PC2tKxaWlkqj8qpmE1S4DcNTXTnid7) and report back whether this solves the issue.

**Comment by DeadFrostt** [comment] 2024-02-19 19:06
> For those affected by this issue, please try this new [test build](https://drive.google.com/file/d/1I8PC2tKxaWlkqj8qpmE1S4DcNTXTnid7) and report back whether this solves the issue.

Thank you for the reply, sorry to say but it did not fix the issue I did a clean install and it did not seem to work I still get the same error.

**Comment by Black-Seraph** [comment] 2024-02-19 22:37
Version 1.3.2 has dropped since that post dropped, please re-try with that version, then export and attach your application event log.

**Comment by DeadFrostt** [comment] 2024-02-19 22:57
Got the same issue with 1.3.2

Log Name:      Application
Source:        Duo
Date:          2/19/2024 4:49:05 PM
Event ID:      1
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      *
Description:
Failed to apply the display driver patch for main
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Duo" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-19T22:49:05.2495441Z" />
    <EventRecordID>101395</EventRecordID>
    <Correlation />
    <Execution ProcessID="22304" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>harshilslaptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Failed to apply the display driver patch for main</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Duo
Date:          2/19/2024 4:47:43 PM
Event ID:      1
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      *
Description:
Stopped main
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Duo" />
    <EventID Qualifiers="0">1</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-19T22:47:43.0906873Z" />
    <EventRecordID>101394</EventRecordID>
    <Correlation />
    <Execution ProcessID="26804" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>harshilslaptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Stopped main</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Microsoft-Windows-RestartManager
Date:          2/19/2024 4:47:38 PM
Event ID:      10001
Task Category: None
Level:         Information
Keywords:      
User:          *
Computer:      *
Description:
Ending session 1 started ‎2024‎-‎02‎-‎19T22:46:58.900609000Z.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RestartManager" Guid="{0888e5ef-9b98-4695-979d-e92ce4247224}" />
    <EventID>10001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-19T22:47:38.7965409Z" />
    <EventRecordID>101393</EventRecordID>
    <Correlation />
    <Execution ProcessID="8936" ThreadID="21864" />
    <Channel>Application</Channel>
    <Computer>harshilslaptop</Computer>
    <Security UserID="S-1-5-21-22970823-1069987442-3661973824-1001" />
  </System>
  <UserData>
    <RmSessionEvent xmlns="http://www.microsoft.com/2005/08/Windows/Reliability/RestartManager/">
      <RmSessionId>1</RmSessionId>
      <UTCStartTime>2024-02-19T22:46:58.9006090Z</UTCStartTime>
    </RmSessionEvent>
  </UserData>
</Event>

Log Name:      Application
Source:        SecurityCenter
Date:          2/19/2024 4:47:08 PM
Event ID:      15
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      *
Description:
Updated Windows Defender status successfully to SECURITY_PRODUCT_STATE_SNOOZED.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SecurityCenter" />
    <EventID Qualifiers="0">15</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-19T22:47:08.6892380Z" />
    <EventRecordID>101392</EventRecordID>
    <Correlation />
    <Execution ProcessID="2248" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>harshilslaptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Windows Defender</Data>
    <Data>SECURITY_PRODUCT_STATE_SNOOZED</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Microsoft-Windows-RestartManager
Date:          2/19/2024 4:46:58 PM
Event ID:      10000
Task Category: None
Level:         Information
Keywords:      
User:          *
Computer:      *
Description:
Starting session 1 - ‎2024‎-‎02‎-‎19T22:46:58.900609000Z.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RestartManager" Guid="{0888e5ef-9b98-4695-979d-e92ce4247224}" />
    <EventID>10000</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-19T22:46:58.9019604Z" />
    <EventRecordID>101391</EventRecordID>
    <Correlation />
    <Execution ProcessID="8936" ThreadID="21864" />
    <Channel>Application</Channel>
    <Computer>harshilslaptop</Computer>
    <Security UserID="S-1-5-21-22970823-1069987442-3661973824-1001" />
  </System>
  <UserData>
    <RmSessionEvent xmlns="http://www.microsoft.com/2005/08/Windows/Reliability/RestartManager/">
      <RmSessionId>1</RmSessionId>
      
      LOG
      
      https://drive.google.com/file/d/1_BwZbUIsOX1sAA8oW7Wot_Q4spoAIytY/view?usp=sharing

**Comment by Black-Seraph** [comment] 2024-02-20 13:17
Do you happen to have a third party antivirus software installed @DeadFrostt?

**Comment by DeadFrostt** [comment] 2024-02-21 17:18
I do not have a third party antivirus installed. Regarding the second part, I can stream the registery somewhere either on teamviewer or discord so its both safe for you and me if thats okay with you.

**Comment by DeadFrostt** [comment] 2024-02-21 17:21
This may be helpful but , the first time I installed DUO it was blocked by windows defender and after that things have been like this.

**Comment by Black-Seraph** [comment] 2024-02-27 16:54
Closing for inactivity.

**Closed by Black-Seraph** 2024-02-27 16:54 UTC
