### ISSUE TITLE
Build 1.3.1 Breaks GamePad Jailing.

### ISSUE THREAD

**Issue by XeosCeleres** [DuoStream/Duo#54] opened 2024-02-19 14:28 UTC
Reverting back to Build 1.3.0 solves it.

**Issue:** When using a game controller on a Duo Instance. It registers every action on the host PC.
This issue was reported, investigated, and fixed before at https://github.com/DuoStream/Duo/issues/35

**Comment by Black-Seraph** [comment] 2024-02-19 14:37
Build 1.3.1 had no input related changes at all, and I can't reproduce your issue at all.

Also, you haven't attached **any logs at all**.

No logs -> No fix.

**Comment by XeosCeleres** [comment] 2024-02-19 18:24
[SteamDeck.log](https://github.com/DuoStream/Duo/files/14335781/SteamDeck.log)
Hope this helps. Thanks for all you do!

**Comment by Black-Seraph** [comment] 2024-02-19 22:20
Okay, your log doesn't show any gamepad jailing attempts at all, but it does show it resolving the ViGEmBus root address and the gamepad being detected.

Did you modify any of the Sunshine web panel settings?
If so, could you also attach your instance's Sunshine configuration file?

It should be in the same location as the instance's log file.

**Comment by XeosCeleres** [comment] 2024-02-20 08:08
[SteamDeck.zip](https://github.com/DuoStream/Duo/files/14341252/SteamDeck.zip)
I've followed the instructions above an upgraded 1.3.0 to 1.3.2, and replaced the Sunshine.exe. Jailing fails again.

I've attached both log and conf file as a zip. Couldn't upload .conf here. Let me know if you need anything else. Thanks!

**Comment by Black-Seraph** [comment] 2024-02-20 13:14
Do you have HidHide installed by chance?

I don't see any child device nodes under your ViGEmBus root node, which should be impossible otherwise.

**Comment by XeosCeleres** [comment] 2024-02-20 13:20
No, I don’t have HidHide installed. Didn’t install it before as it was demised already after you got Nefarious to help.

**Comment by Black-Seraph** [comment] 2024-02-20 13:32
No worries. We will inch our way forward, crossing potential causes off one item at a time by rule of exclusion.

Here's what we need to do next (to figure out where exactly your device is spawning):

1. Start up your Duo instance.
2. Connect a gamepad to your Moonlight client and connect to the instance.
3. Inside your instance's session, open the Device Manager.
4. Inside the Device Manager click on View, then Devices by container.
5. In the list of devices, find your offending gamepad, right-click it and click on Properties.
6. Click on the Details tab.
7. Click on the Property combo box and choose Device instance path, then copy its value into a notepad.
8. Click on the Property combo box and choose Parent, then copy its value into a notepad.
9. Click on the Property combo box and choose Last known parent, then copy its value into a notepad.
10. Finally, open your Start Menu, search for PowerShell, right-click PowerShell and run it as administrator.
11. Execute the following command: Get-WmiObject Win32_PNPEntity | Out-File -FilePath C:\DeviceList.txt
12. Upload the DeviceList.txt file found in your C:\ drive along with the previously copied notepad data.

Armed with this data I should be able to figure out where exactly your device is hiding.

**Comment by XeosCeleres** [comment] 2024-02-20 14:18
Please find what you requested for attached. 

**Note that for #2**: I don't need to connect an external GamePad because i Use a SteamDeck. I assume that HID 'Xbox 360 Controller for Windows' is the GamePad itself. This is where the data is derived from.

[Xbox 360 Controller for Windows.txt](https://github.com/DuoStream/Duo/files/14345613/Xbox.360.Controller.for.Windows.txt)
[DeviceList.txt](https://github.com/DuoStream/Duo/files/14345614/DeviceList.txt)

**Comment by Black-Seraph** [comment] 2024-02-20 15:48
Your ViGEmBus installation is corrupt.

You have two ViGEmBus root hub devices on your system, one located at ROOT\SYSTEM\0002 and a second one, located at ROOT\SYSTEM\0003.

ViGEmBus malfunctions when multiple virtual hubs are present.

I figure that your setup must have gotten busted as part of a ViGEmBus update at some point in time, which it is known to do.

Here's how you can fix it:

1. Stop Duo, if it is running that is.
2. Uninstall ViGEmBus via Windows' **Add or remove programs** menu.
3. Open **Device Manager** and unfold the **System devices** node.
4. Right-click every remaining **Nefarius Virtual Gamepad Emulation Bus** you can find, click on **Uninstall device**, and tick the **Attempt to remove the driver for this device** checkbox before clicking on **Uninstall**.
5. Reboot the computer.
6. Re-install the latest ViGEmBus version.
7. Reboot the computer again.
8. Restart Duo.

Finally, let us know if this solved your issue.

If it did, I'll add it to the Wiki's upcoming troubleshooting section.

**Comment by Black-Seraph** [comment] 2024-02-20 21:16
So the order to fix this should be:

1. Manually remove all ViGEmBus root devices
2. Uninstall ViGEmBus
3. Reboot
4. Install ViGEmBus
5. Reboot

Glad we finally figured this one out.

I'll add it to the wiki along with a few other troubleshooting bits tomorrow after work then.

Issue closed.

**Closed by Black-Seraph** 2024-02-20 21:16 UTC
