### ISSUE TITLE
Can’t launch 

### ISSUE THREAD

**Issue by shustovcreates** [DuoStream/Duo#1] opened 2023-10-19 11:21 UTC
Hi!
For some reason can’t launch DuoStream. It just turns off by itself.  Tried reinstalling it, rebooting. Please help!
Specs are Windows 11, ryzen 5700g and rtx 3060 

https://github.com/DuoStream/Duo/assets/67076067/947b73f6-9b6d-4702-a87f-75bf259f71a3

**Comment by project-sbc** [comment] 2023-10-19 19:45
if you check event viewer, you might see an error like "unable to add user to remote desktop group". Im going out on limb here but im going to guess you need windows 11 pro to make this work. I do not have it, windows 11 22H2, and have the same experience as you. You can manually start sunshine by going to program files, duo, right click it and run as admin. It will run.

**Comment by kuynh** [comment] 2023-10-20 00:08
I have the same issue as @shustovcreates. Starts then turns itself off after a few seconds. Using windows 11 and nvidia gamestream.

**Comment by project-sbc** [comment] 2023-10-20 00:31
I got some feedback from Russ @ retro game corp, he was using windows 11 home, not PRO. He had to create a second account, a local user account instead of windows based account to use. I am still getting an error about adding users to the remote desktop group policy. I went ahead and added the gpedit.msc for windows home version but it doesn't automatically create the remote user group. Still investigating further. I did ping the developer on X for potentially more help

**Comment by shustovcreates** [comment] 2023-10-20 07:44
May the reason be that I use Windows 11 Home edition and not the Pro version?

**Comment by shustovcreates** [comment] 2023-10-20 07:56
Tried downloading [this software](https://github.com/proviq/AccountManagement) to create group named "Remote Desktop Users " as event manager says (The user "your usernem"couldn't be added to the Remote Desktop Users group). And adding my new local user account manually. Didn't work.

**Comment by tognerijones** [comment] 2023-10-21 03:15
Same issue, huge bummer.

**Comment by Black-Seraph** [comment] 2023-10-21 05:40
I'd need to take a look at an affected computer to really be able to tell what the problem is, but to clarify a few points that came up in the comments here so far:

- Any Windows 11 version 22H2 or newer is compatible
- Windows Home is plenty
- If you get an error message about the "Remote Desktop Users" group in your application event log then something is wrong with your Windows account (my guess is that the account is linked to a Microsoft account, in which case the steps shown in the Known Issues section will help)
- If you get an error about RdpIdd capture patch injection, that could be caused by AV software, currently unknown Windows updates or Network Level Authentication errors (maybe it's disabled on your system)

If any of you need additional help figuring this out I suggest getting in touch with me via Discord @ black5eraph, but keep in mind I'll have to take a look at your system to tell you more which, at the bare minimum means Discord screen share.

**Comment by Black-Seraph** [comment] 2023-10-21 06:23
I was able to confirm the issue on a Windows 11 Home install and a fix has been released.

To those affected: Please re-try with version 1.0.5.

**Closed by Black-Seraph** 2023-10-21 06:23 UTC

**Comment by laurorual** [comment] 2023-10-21 20:26
> I was able to confirm the issue on a Windows 11 Home install and a fix has been released.
> 
> To those affected: Please re-try with version 1.0.5.

it's working now!
just tried using my main account (a microsoft account, was trying to see if it would work without creating a new local user) and everything worked as expected!
Really cool app.
