### ISSUE TITLE
sunshine doesn't start and duo is not working, but creates constant cpu load

### ISSUE THREAD

**Issue by mikney** [DuoStream/Duo#51] opened 2024-02-18 13:00 UTC
web admin panel sunchine doesn't open - This site can’t be reached. I also don't see the sunchine process in task manager. Before installed duo i already have had sunshine, maybe this is problem? 
Windows 11 Pro 22H2
![Screenshot_315](https://github.com/DuoStream/Duo/assets/78865970/c9dbbd20-03e1-4907-8c18-56dc712bb17d)
![Screenshot_316](https://github.com/DuoStream/Duo/assets/78865970/30ab6b07-2c4c-4400-b2d7-e545c31c74b5)

**Comment by mikney** [comment] 2024-02-18 14:04
eventually, have same issue in event log https://github.com/DuoStream/Duo/issues/47

**Comment by mikney** [comment] 2024-02-18 19:23
also tried run manually sunchine in duo and have this errors. I also tried standalone sunchine, thers is no errors and problems
![Screenshot_318](https://github.com/DuoStream/Duo/assets/78865970/f28f3f84-366b-4982-864e-bc2251d09b3c)

**Comment by Black-Seraph** [comment] 2024-02-18 21:34
You can't run Duo's sunshine fork in a regular console session.

Regular builds of sunshine capture the console session framebuffer via DXGI screen duplication, while Duo captures its framebuffer via a IddCx swapchain hook, combined with cross-device NT-handle shared surface textures.

Those are two completely different ways of capturing images, and as such the adapter error messages you're seeing are to-be-expected.

This issue is also a duplicate of #47.
As such, I'll be closing this one, so please continue discussion about this issue there.

Please read through issue #47 and provide the information I've already asked of other people in there, namely:

- A screenshot of your RDP_CnC.exe status
- An export of your application event log
- And if possible, an instance log file created by Duo

If your computer is joined to a domain, I'll also need to know if any group policies have been applied to it, and if so, which ones.

**Closed by Black-Seraph** 2024-02-18 21:34 UTC
